// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateNodeArgs {
    pub id: u64,
    pub type_id: String,
    pub display_name: String,
    pub x: f32,
    pub y: f32,
    pub params: String,
}

impl From<CreateNodeArgs> for super::Reducer {
    fn from(args: CreateNodeArgs) -> Self {
        Self::CreateNode {
            id: args.id,
            type_id: args.type_id,
            display_name: args.display_name,
            x: args.x,
            y: args.y,
            params: args.params,
        }
    }
}

impl __sdk::InModule for CreateNodeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_node`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_node {
    /// Request that the remote module invoke the reducer `create_node` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_node:create_node_then`] to run a callback after the reducer completes.
    fn create_node(
        &self,
        id: u64,
        type_id: String,
        display_name: String,
        x: f32,
        y: f32,
        params: String,
    ) -> __sdk::Result<()> {
        self.create_node_then(id, type_id, display_name, x, y, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_node` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_node_then(
        &self,
        id: u64,
        type_id: String,
        display_name: String,
        x: f32,
        y: f32,
        params: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_node for super::RemoteReducers {
    fn create_node_then(
        &self,
        id: u64,
        type_id: String,
        display_name: String,
        x: f32,
        y: f32,
        params: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateNodeArgs {
                id,
                type_id,
                display_name,
                x,
                y,
                params,
            },
            callback,
        )
    }
}
