// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DisconnectEdgeArgs {
    pub id: u64,
}

impl From<DisconnectEdgeArgs> for super::Reducer {
    fn from(args: DisconnectEdgeArgs) -> Self {
        Self::DisconnectEdge { id: args.id }
    }
}

impl __sdk::InModule for DisconnectEdgeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `disconnect_edge`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait disconnect_edge {
    /// Request that the remote module invoke the reducer `disconnect_edge` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`disconnect_edge:disconnect_edge_then`] to run a callback after the reducer completes.
    fn disconnect_edge(&self, id: u64) -> __sdk::Result<()> {
        self.disconnect_edge_then(id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `disconnect_edge` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn disconnect_edge_then(
        &self,
        id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl disconnect_edge for super::RemoteReducers {
    fn disconnect_edge_then(
        &self,
        id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DisconnectEdgeArgs { id }, callback)
    }
}
