// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::edge_type::Edge;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `edge`.
///
/// Obtain a handle from the [`EdgeTableAccess::edge`] method on [`super::RemoteTables`],
/// like `ctx.db.edge()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.edge().on_insert(...)`.
pub struct EdgeTableHandle<'ctx> {
    imp: __sdk::TableHandle<Edge>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `edge`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EdgeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EdgeTableHandle`], which mediates access to the table `edge`.
    fn edge(&self) -> EdgeTableHandle<'_>;
}

impl EdgeTableAccess for super::RemoteTables {
    fn edge(&self) -> EdgeTableHandle<'_> {
        EdgeTableHandle {
            imp: self.imp.get_table::<Edge>("edge"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EdgeInsertCallbackId(__sdk::CallbackId);
pub struct EdgeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EdgeTableHandle<'ctx> {
    type Row = Edge;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Edge> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EdgeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EdgeInsertCallbackId {
        EdgeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EdgeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EdgeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EdgeDeleteCallbackId {
        EdgeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EdgeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EdgeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EdgeTableHandle<'ctx> {
    type UpdateCallbackId = EdgeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EdgeUpdateCallbackId {
        EdgeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EdgeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `edge`,
/// which allows point queries on the field of the same name
/// via the [`EdgeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.edge().id().find(...)`.
pub struct EdgeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Edge, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EdgeTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `edge`.
    pub fn id(&self) -> EdgeIdUnique<'ctx> {
        EdgeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EdgeIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Edge> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Edge>("edge");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Edge>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Edge>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Edge`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait edgeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Edge`.
    fn edge(&self) -> __sdk::__query_builder::Table<Edge>;
}

impl edgeQueryTableAccess for __sdk::QueryTableAccessor {
    fn edge(&self) -> __sdk::__query_builder::Table<Edge> {
        __sdk::__query_builder::Table::new("edge")
    }
}
