// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::node_type::Node;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `node`.
///
/// Obtain a handle from the [`NodeTableAccess::node`] method on [`super::RemoteTables`],
/// like `ctx.db.node()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.node().on_insert(...)`.
pub struct NodeTableHandle<'ctx> {
    imp: __sdk::TableHandle<Node>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `node`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NodeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NodeTableHandle`], which mediates access to the table `node`.
    fn node(&self) -> NodeTableHandle<'_>;
}

impl NodeTableAccess for super::RemoteTables {
    fn node(&self) -> NodeTableHandle<'_> {
        NodeTableHandle {
            imp: self.imp.get_table::<Node>("node"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NodeInsertCallbackId(__sdk::CallbackId);
pub struct NodeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NodeTableHandle<'ctx> {
    type Row = Node;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Node> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NodeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeInsertCallbackId {
        NodeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NodeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NodeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeDeleteCallbackId {
        NodeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NodeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NodeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NodeTableHandle<'ctx> {
    type UpdateCallbackId = NodeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NodeUpdateCallbackId {
        NodeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NodeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `node`,
/// which allows point queries on the field of the same name
/// via the [`NodeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.node().id().find(...)`.
pub struct NodeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Node, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NodeTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `node`.
    pub fn id(&self) -> NodeIdUnique<'ctx> {
        NodeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NodeIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Node> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Node>("node");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Node>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Node>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Node`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait nodeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Node`.
    fn node(&self) -> __sdk::__query_builder::Table<Node>;
}

impl nodeQueryTableAccess for __sdk::QueryTableAccessor {
    fn node(&self) -> __sdk::__query_builder::Table<Node> {
        __sdk::__query_builder::Table::new("node")
    }
}
