// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Node {
    pub id: u64,
    pub type_id: String,
    pub display_name: String,
    pub x: f32,
    pub y: f32,
    pub params: String,
}

impl __sdk::InModule for Node {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Node`.
///
/// Provides typed access to columns for query building.
pub struct NodeCols {
    pub id: __sdk::__query_builder::Col<Node, u64>,
    pub type_id: __sdk::__query_builder::Col<Node, String>,
    pub display_name: __sdk::__query_builder::Col<Node, String>,
    pub x: __sdk::__query_builder::Col<Node, f32>,
    pub y: __sdk::__query_builder::Col<Node, f32>,
    pub params: __sdk::__query_builder::Col<Node, String>,
}

impl __sdk::__query_builder::HasCols for Node {
    type Cols = NodeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NodeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            type_id: __sdk::__query_builder::Col::new(table_name, "type_id"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            params: __sdk::__query_builder::Col::new(table_name, "params"),
        }
    }
}

/// Indexed column accessor struct for the table `Node`.
///
/// Provides typed access to indexed columns for query building.
pub struct NodeIxCols {
    pub id: __sdk::__query_builder::IxCol<Node, u64>,
}

impl __sdk::__query_builder::HasIxCols for Node {
    type IxCols = NodeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NodeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Node {}
