// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetNodeParamsArgs {
    pub id: u64,
    pub params: String,
}

impl From<SetNodeParamsArgs> for super::Reducer {
    fn from(args: SetNodeParamsArgs) -> Self {
        Self::SetNodeParams {
            id: args.id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for SetNodeParamsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_node_params`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_node_params {
    /// Request that the remote module invoke the reducer `set_node_params` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_node_params:set_node_params_then`] to run a callback after the reducer completes.
    fn set_node_params(&self, id: u64, params: String) -> __sdk::Result<()> {
        self.set_node_params_then(id, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_node_params` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_node_params_then(
        &self,
        id: u64,
        params: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_node_params for super::RemoteReducers {
    fn set_node_params_then(
        &self,
        id: u64,
        params: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetNodeParamsArgs { id, params }, callback)
    }
}
