// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdoptRootNodesArgs {
    pub graph_id: u64,
    pub runner: String,
}

impl From<AdoptRootNodesArgs> for super::Reducer {
    fn from(args: AdoptRootNodesArgs) -> Self {
        Self::AdoptRootNodes {
            graph_id: args.graph_id,
            runner: args.runner,
        }
    }
}

impl __sdk::InModule for AdoptRootNodesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `adopt_root_nodes`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait adopt_root_nodes {
    /// Request that the remote module invoke the reducer `adopt_root_nodes` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`adopt_root_nodes:adopt_root_nodes_then`] to run a callback after the reducer completes.
    fn adopt_root_nodes(&self, graph_id: u64, runner: String) -> __sdk::Result<()> {
        self.adopt_root_nodes_then(graph_id, runner, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `adopt_root_nodes` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn adopt_root_nodes_then(
        &self,
        graph_id: u64,
        runner: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl adopt_root_nodes for super::RemoteReducers {
    fn adopt_root_nodes_then(
        &self,
        graph_id: u64,
        runner: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdoptRootNodesArgs { graph_id, runner }, callback)
    }
}
