// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AnnounceFeedArgs {
    pub addr: String,
    pub cert: String,
}

impl From<AnnounceFeedArgs> for super::Reducer {
    fn from(args: AnnounceFeedArgs) -> Self {
        Self::AnnounceFeed {
            addr: args.addr,
            cert: args.cert,
        }
    }
}

impl __sdk::InModule for AnnounceFeedArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `announce_feed`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait announce_feed {
    /// Request that the remote module invoke the reducer `announce_feed` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`announce_feed:announce_feed_then`] to run a callback after the reducer completes.
    fn announce_feed(&self, addr: String, cert: String) -> __sdk::Result<()> {
        self.announce_feed_then(addr, cert, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `announce_feed` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn announce_feed_then(
        &self,
        addr: String,
        cert: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl announce_feed for super::RemoteReducers {
    fn announce_feed_then(
        &self,
        addr: String,
        cert: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AnnounceFeedArgs { addr, cert }, callback)
    }
}
