// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClearNodeOutputsArgs {
    pub node_id: u64,
}

impl From<ClearNodeOutputsArgs> for super::Reducer {
    fn from(args: ClearNodeOutputsArgs) -> Self {
        Self::ClearNodeOutputs {
            node_id: args.node_id,
        }
    }
}

impl __sdk::InModule for ClearNodeOutputsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `clear_node_outputs`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait clear_node_outputs {
    /// Request that the remote module invoke the reducer `clear_node_outputs` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`clear_node_outputs:clear_node_outputs_then`] to run a callback after the reducer completes.
    fn clear_node_outputs(&self, node_id: u64) -> __sdk::Result<()> {
        self.clear_node_outputs_then(node_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `clear_node_outputs` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn clear_node_outputs_then(
        &self,
        node_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl clear_node_outputs for super::RemoteReducers {
    fn clear_node_outputs_then(
        &self,
        node_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ClearNodeOutputsArgs { node_id }, callback)
    }
}
