// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ConnectEdgeArgs {
    pub id: u64,
    pub from_node: u64,
    pub from_pin: String,
    pub to_node: u64,
    pub to_pin: String,
}

impl From<ConnectEdgeArgs> for super::Reducer {
    fn from(args: ConnectEdgeArgs) -> Self {
        Self::ConnectEdge {
            id: args.id,
            from_node: args.from_node,
            from_pin: args.from_pin,
            to_node: args.to_node,
            to_pin: args.to_pin,
        }
    }
}

impl __sdk::InModule for ConnectEdgeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `connect_edge`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait connect_edge {
    /// Request that the remote module invoke the reducer `connect_edge` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`connect_edge:connect_edge_then`] to run a callback after the reducer completes.
    fn connect_edge(
        &self,
        id: u64,
        from_node: u64,
        from_pin: String,
        to_node: u64,
        to_pin: String,
    ) -> __sdk::Result<()> {
        self.connect_edge_then(id, from_node, from_pin, to_node, to_pin, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `connect_edge` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn connect_edge_then(
        &self,
        id: u64,
        from_node: u64,
        from_pin: String,
        to_node: u64,
        to_pin: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl connect_edge for super::RemoteReducers {
    fn connect_edge_then(
        &self,
        id: u64,
        from_node: u64,
        from_pin: String,
        to_node: u64,
        to_pin: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ConnectEdgeArgs {
                id,
                from_node,
                from_pin,
                to_node,
                to_pin,
            },
            callback,
        )
    }
}
