// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Edge {
    pub id: u64,
    pub from_node: u64,
    pub from_pin: String,
    pub to_node: u64,
    pub to_pin: String,
}

impl __sdk::InModule for Edge {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Edge`.
///
/// Provides typed access to columns for query building.
pub struct EdgeCols {
    pub id: __sdk::__query_builder::Col<Edge, u64>,
    pub from_node: __sdk::__query_builder::Col<Edge, u64>,
    pub from_pin: __sdk::__query_builder::Col<Edge, String>,
    pub to_node: __sdk::__query_builder::Col<Edge, u64>,
    pub to_pin: __sdk::__query_builder::Col<Edge, String>,
}

impl __sdk::__query_builder::HasCols for Edge {
    type Cols = EdgeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EdgeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            from_node: __sdk::__query_builder::Col::new(table_name, "from_node"),
            from_pin: __sdk::__query_builder::Col::new(table_name, "from_pin"),
            to_node: __sdk::__query_builder::Col::new(table_name, "to_node"),
            to_pin: __sdk::__query_builder::Col::new(table_name, "to_pin"),
        }
    }
}

/// Indexed column accessor struct for the table `Edge`.
///
/// Provides typed access to indexed columns for query building.
pub struct EdgeIxCols {
    pub id: __sdk::__query_builder::IxCol<Edge, u64>,
}

impl __sdk::__query_builder::HasIxCols for Edge {
    type IxCols = EdgeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EdgeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Edge {}
