// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveNodeArgs {
    pub id: u64,
    pub x: f32,
    pub y: f32,
}

impl From<MoveNodeArgs> for super::Reducer {
    fn from(args: MoveNodeArgs) -> Self {
        Self::MoveNode {
            id: args.id,
            x: args.x,
            y: args.y,
        }
    }
}

impl __sdk::InModule for MoveNodeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_node`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_node {
    /// Request that the remote module invoke the reducer `move_node` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`move_node:move_node_then`] to run a callback after the reducer completes.
    fn move_node(&self, id: u64, x: f32, y: f32) -> __sdk::Result<()> {
        self.move_node_then(id, x, y, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `move_node` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn move_node_then(
        &self,
        id: u64,
        x: f32,
        y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl move_node for super::RemoteReducers {
    fn move_node_then(
        &self,
        id: u64,
        x: f32,
        y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MoveNodeArgs { id, x, y }, callback)
    }
}
