// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NodeOutput {
    pub key: String,
    pub node_id: u64,
    pub pin: String,
    pub ty: String,
    pub value: String,
}

impl __sdk::InModule for NodeOutput {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NodeOutput`.
///
/// Provides typed access to columns for query building.
pub struct NodeOutputCols {
    pub key: __sdk::__query_builder::Col<NodeOutput, String>,
    pub node_id: __sdk::__query_builder::Col<NodeOutput, u64>,
    pub pin: __sdk::__query_builder::Col<NodeOutput, String>,
    pub ty: __sdk::__query_builder::Col<NodeOutput, String>,
    pub value: __sdk::__query_builder::Col<NodeOutput, String>,
}

impl __sdk::__query_builder::HasCols for NodeOutput {
    type Cols = NodeOutputCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NodeOutputCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            node_id: __sdk::__query_builder::Col::new(table_name, "node_id"),
            pin: __sdk::__query_builder::Col::new(table_name, "pin"),
            ty: __sdk::__query_builder::Col::new(table_name, "ty"),
            value: __sdk::__query_builder::Col::new(table_name, "value"),
        }
    }
}

/// Indexed column accessor struct for the table `NodeOutput`.
///
/// Provides typed access to indexed columns for query building.
pub struct NodeOutputIxCols {
    pub key: __sdk::__query_builder::IxCol<NodeOutput, String>,
}

impl __sdk::__query_builder::HasIxCols for NodeOutput {
    type IxCols = NodeOutputIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NodeOutputIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NodeOutput {}
