// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::node_trigger_type::NodeTrigger;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `node_trigger`.
///
/// Obtain a handle from the [`NodeTriggerTableAccess::node_trigger`] method on [`super::RemoteTables`],
/// like `ctx.db.node_trigger()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.node_trigger().on_insert(...)`.
pub struct NodeTriggerTableHandle<'ctx> {
    imp: __sdk::TableHandle<NodeTrigger>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `node_trigger`.
pub struct NodeTriggerTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for NodeTriggerTableAccessor {
    type Row = NodeTrigger;
    type Handle<'db> = NodeTriggerTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.node_trigger()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `node_trigger`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NodeTriggerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NodeTriggerTableHandle`], which mediates access to the table `node_trigger`.
    fn node_trigger(&self) -> NodeTriggerTableHandle<'_>;
}

impl NodeTriggerTableAccess for super::RemoteTables {
    fn node_trigger(&self) -> NodeTriggerTableHandle<'_> {
        NodeTriggerTableHandle {
            imp: self.imp.get_table::<NodeTrigger>("node_trigger"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NodeTriggerInsertCallbackId(__sdk::CallbackId);
pub struct NodeTriggerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for NodeTriggerTableHandle<'ctx> {
    type Row = NodeTrigger;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NodeTrigger> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for NodeTriggerTableHandle<'ctx> {
    type Row = NodeTrigger;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NodeTrigger> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NodeTriggerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeTriggerInsertCallbackId {
        NodeTriggerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NodeTriggerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NodeTriggerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeTriggerDeleteCallbackId {
        NodeTriggerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NodeTriggerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for NodeTriggerTableHandle<'ctx> {
    type InsertCallbackId = NodeTriggerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeTriggerInsertCallbackId {
        NodeTriggerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NodeTriggerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for NodeTriggerTableHandle<'ctx> {
    type DeleteCallbackId = NodeTriggerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeTriggerDeleteCallbackId {
        NodeTriggerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NodeTriggerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NodeTriggerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NodeTriggerTableHandle<'ctx> {
    type UpdateCallbackId = NodeTriggerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NodeTriggerUpdateCallbackId {
        NodeTriggerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NodeTriggerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for NodeTriggerTableHandle<'ctx> {
    type UpdateCallbackId = NodeTriggerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NodeTriggerUpdateCallbackId {
        NodeTriggerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NodeTriggerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `node_id` unique index on the table `node_trigger`,
/// which allows point queries on the field of the same name
/// via the [`NodeTriggerNodeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.node_trigger().node_id().find(...)`.
pub struct NodeTriggerNodeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NodeTrigger, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NodeTriggerTableHandle<'ctx> {
    /// Get a handle on the `node_id` unique index on the table `node_trigger`.
    pub fn node_id(&self) -> NodeTriggerNodeIdUnique<'ctx> {
        NodeTriggerNodeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("node_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NodeTriggerNodeIdUnique<'ctx> {
    /// Find the subscribed row whose `node_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NodeTrigger> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NodeTrigger>("node_trigger");
    _table.add_unique_constraint::<u64>("node_id", |row| &row.node_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NodeTrigger>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NodeTrigger>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NodeTrigger`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait node_triggerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NodeTrigger`.
    fn node_trigger(&self) -> __sdk::__query_builder::Table<NodeTrigger>;
}

impl node_triggerQueryTableAccess for __sdk::QueryTableAccessor {
    fn node_trigger(&self) -> __sdk::__query_builder::Table<NodeTrigger> {
        __sdk::__query_builder::Table::new("node_trigger")
    }
}
