// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::node_output_type::NodeOutput;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `node_output`.
///
/// Obtain a handle from the [`NodeOutputTableAccess::node_output`] method on [`super::RemoteTables`],
/// like `ctx.db.node_output()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.node_output().on_insert(...)`.
pub struct NodeOutputTableHandle<'ctx> {
    imp: __sdk::TableHandle<NodeOutput>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `node_output`.
pub struct NodeOutputTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for NodeOutputTableAccessor {
    type Row = NodeOutput;
    type Handle<'db> = NodeOutputTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.node_output()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `node_output`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NodeOutputTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NodeOutputTableHandle`], which mediates access to the table `node_output`.
    fn node_output(&self) -> NodeOutputTableHandle<'_>;
}

impl NodeOutputTableAccess for super::RemoteTables {
    fn node_output(&self) -> NodeOutputTableHandle<'_> {
        NodeOutputTableHandle {
            imp: self.imp.get_table::<NodeOutput>("node_output"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NodeOutputInsertCallbackId(__sdk::CallbackId);
pub struct NodeOutputDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for NodeOutputTableHandle<'ctx> {
    type Row = NodeOutput;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NodeOutput> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for NodeOutputTableHandle<'ctx> {
    type Row = NodeOutput;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NodeOutput> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NodeOutputInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeOutputInsertCallbackId {
        NodeOutputInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NodeOutputInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NodeOutputDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeOutputDeleteCallbackId {
        NodeOutputDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NodeOutputDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for NodeOutputTableHandle<'ctx> {
    type InsertCallbackId = NodeOutputInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeOutputInsertCallbackId {
        NodeOutputInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NodeOutputInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for NodeOutputTableHandle<'ctx> {
    type DeleteCallbackId = NodeOutputDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeOutputDeleteCallbackId {
        NodeOutputDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NodeOutputDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NodeOutputUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NodeOutputTableHandle<'ctx> {
    type UpdateCallbackId = NodeOutputUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NodeOutputUpdateCallbackId {
        NodeOutputUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NodeOutputUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for NodeOutputTableHandle<'ctx> {
    type UpdateCallbackId = NodeOutputUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NodeOutputUpdateCallbackId {
        NodeOutputUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NodeOutputUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `node_output`,
/// which allows point queries on the field of the same name
/// via the [`NodeOutputKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.node_output().key().find(...)`.
pub struct NodeOutputKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NodeOutput, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NodeOutputTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `node_output`.
    pub fn key(&self) -> NodeOutputKeyUnique<'ctx> {
        NodeOutputKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NodeOutputKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<NodeOutput> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NodeOutput>("node_output");
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NodeOutput>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NodeOutput>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NodeOutput`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait node_outputQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NodeOutput`.
    fn node_output(&self) -> __sdk::__query_builder::Table<NodeOutput>;
}

impl node_outputQueryTableAccess for __sdk::QueryTableAccessor {
    fn node_output(&self) -> __sdk::__query_builder::Table<NodeOutput> {
        __sdk::__query_builder::Table::new("node_output")
    }
}
