// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PublishOutputArgs {
    pub node_id: u64,
    pub pin: String,
    pub ty: String,
    pub value: String,
}

impl From<PublishOutputArgs> for super::Reducer {
    fn from(args: PublishOutputArgs) -> Self {
        Self::PublishOutput {
            node_id: args.node_id,
            pin: args.pin,
            ty: args.ty,
            value: args.value,
        }
    }
}

impl __sdk::InModule for PublishOutputArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `publish_output`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait publish_output {
    /// Request that the remote module invoke the reducer `publish_output` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`publish_output:publish_output_then`] to run a callback after the reducer completes.
    fn publish_output(
        &self,
        node_id: u64,
        pin: String,
        ty: String,
        value: String,
    ) -> __sdk::Result<()> {
        self.publish_output_then(node_id, pin, ty, value, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `publish_output` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn publish_output_then(
        &self,
        node_id: u64,
        pin: String,
        ty: String,
        value: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl publish_output for super::RemoteReducers {
    fn publish_output_then(
        &self,
        node_id: u64,
        pin: String,
        ty: String,
        value: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PublishOutputArgs {
                node_id,
                pin,
                ty,
                value,
            },
            callback,
        )
    }
}
