// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RenameNodeArgs {
    pub id: u64,
    pub display_name: String,
}

impl From<RenameNodeArgs> for super::Reducer {
    fn from(args: RenameNodeArgs) -> Self {
        Self::RenameNode {
            id: args.id,
            display_name: args.display_name,
        }
    }
}

impl __sdk::InModule for RenameNodeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `rename_node`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait rename_node {
    /// Request that the remote module invoke the reducer `rename_node` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`rename_node:rename_node_then`] to run a callback after the reducer completes.
    fn rename_node(&self, id: u64, display_name: String) -> __sdk::Result<()> {
        self.rename_node_then(id, display_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `rename_node` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn rename_node_then(
        &self,
        id: u64,
        display_name: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl rename_node for super::RemoteReducers {
    fn rename_node_then(
        &self,
        id: u64,
        display_name: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RenameNodeArgs { id, display_name }, callback)
    }
}
