// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::edge_type::Edge;
use super::node_type::Node;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReplaceGraphArgs {
    pub nodes: Vec<Node>,
    pub edges: Vec<Edge>,
}

impl From<ReplaceGraphArgs> for super::Reducer {
    fn from(args: ReplaceGraphArgs) -> Self {
        Self::ReplaceGraph {
            nodes: args.nodes,
            edges: args.edges,
        }
    }
}

impl __sdk::InModule for ReplaceGraphArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `replace_graph`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait replace_graph {
    /// Request that the remote module invoke the reducer `replace_graph` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`replace_graph:replace_graph_then`] to run a callback after the reducer completes.
    fn replace_graph(&self, nodes: Vec<Node>, edges: Vec<Edge>) -> __sdk::Result<()> {
        self.replace_graph_then(nodes, edges, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `replace_graph` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn replace_graph_then(
        &self,
        nodes: Vec<Node>,
        edges: Vec<Edge>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl replace_graph for super::RemoteReducers {
    fn replace_graph_then(
        &self,
        nodes: Vec<Node>,
        edges: Vec<Edge>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ReplaceGraphArgs { nodes, edges }, callback)
    }
}
