// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::runtime_type::Runtime;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `runtime`.
///
/// Obtain a handle from the [`RuntimeTableAccess::runtime`] method on [`super::RemoteTables`],
/// like `ctx.db.runtime()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.runtime().on_insert(...)`.
pub struct RuntimeTableHandle<'ctx> {
    imp: __sdk::TableHandle<Runtime>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `runtime`.
pub struct RuntimeTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for RuntimeTableAccessor {
    type Row = Runtime;
    type Handle<'db> = RuntimeTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.runtime()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `runtime`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RuntimeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RuntimeTableHandle`], which mediates access to the table `runtime`.
    fn runtime(&self) -> RuntimeTableHandle<'_>;
}

impl RuntimeTableAccess for super::RemoteTables {
    fn runtime(&self) -> RuntimeTableHandle<'_> {
        RuntimeTableHandle {
            imp: self.imp.get_table::<Runtime>("runtime"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RuntimeInsertCallbackId(__sdk::CallbackId);
pub struct RuntimeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for RuntimeTableHandle<'ctx> {
    type Row = Runtime;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Runtime> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for RuntimeTableHandle<'ctx> {
    type Row = Runtime;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Runtime> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RuntimeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RuntimeInsertCallbackId {
        RuntimeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RuntimeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RuntimeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RuntimeDeleteCallbackId {
        RuntimeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RuntimeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for RuntimeTableHandle<'ctx> {
    type InsertCallbackId = RuntimeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RuntimeInsertCallbackId {
        RuntimeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RuntimeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for RuntimeTableHandle<'ctx> {
    type DeleteCallbackId = RuntimeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RuntimeDeleteCallbackId {
        RuntimeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RuntimeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RuntimeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RuntimeTableHandle<'ctx> {
    type UpdateCallbackId = RuntimeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RuntimeUpdateCallbackId {
        RuntimeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RuntimeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for RuntimeTableHandle<'ctx> {
    type UpdateCallbackId = RuntimeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RuntimeUpdateCallbackId {
        RuntimeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RuntimeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `connection_id` unique index on the table `runtime`,
/// which allows point queries on the field of the same name
/// via the [`RuntimeConnectionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.runtime().connection_id().find(...)`.
pub struct RuntimeConnectionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Runtime, __sdk::ConnectionId>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RuntimeTableHandle<'ctx> {
    /// Get a handle on the `connection_id` unique index on the table `runtime`.
    pub fn connection_id(&self) -> RuntimeConnectionIdUnique<'ctx> {
        RuntimeConnectionIdUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::ConnectionId>("connection_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RuntimeConnectionIdUnique<'ctx> {
    /// Find the subscribed row whose `connection_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::ConnectionId) -> Option<Runtime> {
        self.imp.find(col_val)
    }
}

/// Access to the `seq` unique index on the table `runtime`,
/// which allows point queries on the field of the same name
/// via the [`RuntimeSeqUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.runtime().seq().find(...)`.
pub struct RuntimeSeqUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Runtime, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RuntimeTableHandle<'ctx> {
    /// Get a handle on the `seq` unique index on the table `runtime`.
    pub fn seq(&self) -> RuntimeSeqUnique<'ctx> {
        RuntimeSeqUnique {
            imp: self.imp.get_unique_constraint::<u64>("seq"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RuntimeSeqUnique<'ctx> {
    /// Find the subscribed row whose `seq` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Runtime> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Runtime>("runtime");
    _table.add_unique_constraint::<__sdk::ConnectionId>("connection_id", |row| &row.connection_id);
    _table.add_unique_constraint::<u64>("seq", |row| &row.seq);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Runtime>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Runtime>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Runtime`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait runtimeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Runtime`.
    fn runtime(&self) -> __sdk::__query_builder::Table<Runtime>;
}

impl runtimeQueryTableAccess for __sdk::QueryTableAccessor {
    fn runtime(&self) -> __sdk::__query_builder::Table<Runtime> {
        __sdk::__query_builder::Table::new("runtime")
    }
}
