// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Runtime {
    pub connection_id: __sdk::ConnectionId,
    pub identity: __sdk::Identity,
    pub seq: u64,
    pub addr: String,
}

impl __sdk::InModule for Runtime {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Runtime`.
///
/// Provides typed access to columns for query building.
pub struct RuntimeCols {
    pub connection_id: __sdk::__query_builder::Col<Runtime, __sdk::ConnectionId>,
    pub identity: __sdk::__query_builder::Col<Runtime, __sdk::Identity>,
    pub seq: __sdk::__query_builder::Col<Runtime, u64>,
    pub addr: __sdk::__query_builder::Col<Runtime, String>,
}

impl __sdk::__query_builder::HasCols for Runtime {
    type Cols = RuntimeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RuntimeCols {
            connection_id: __sdk::__query_builder::Col::new(table_name, "connection_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            seq: __sdk::__query_builder::Col::new(table_name, "seq"),
            addr: __sdk::__query_builder::Col::new(table_name, "addr"),
        }
    }
}

/// Indexed column accessor struct for the table `Runtime`.
///
/// Provides typed access to indexed columns for query building.
pub struct RuntimeIxCols {
    pub connection_id: __sdk::__query_builder::IxCol<Runtime, __sdk::ConnectionId>,
    pub seq: __sdk::__query_builder::IxCol<Runtime, u64>,
}

impl __sdk::__query_builder::HasIxCols for Runtime {
    type IxCols = RuntimeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RuntimeIxCols {
            connection_id: __sdk::__query_builder::IxCol::new(table_name, "connection_id"),
            seq: __sdk::__query_builder::IxCol::new(table_name, "seq"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Runtime {}
